## Numpy Array Operations

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[0:2])
print("Step Slicing: ", arr[0:2:3])
print("Negative Slicing: ", arr[-3])

Basic Slicing:  [1 2]
Step Slicing:  [1]
Negative Slicing:  8


In [15]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element: ", arr_2d[1,-2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:,1])

Specific Element:  5
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [24]:
unsorted = np.array([3,2,5,7,4,6,9,8,1,0,7])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [5, 4]])
print("Unsorted 2D array: \n", arr_2d_unsorted)
print("Sorted 2D array by row: \n", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by column: \n", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [0 1 2 3 4 5 6 7 7 8 9]
Unsorted 2D array: 
 [[3 1]
 [1 2]
 [5 4]]
Sorted 2D array by row: 
 [[1 1]
 [3 2]
 [5 4]]
Sorted 2D array by column: 
 [[1 3]
 [1 2]
 [4 5]]


## Filter

In [25]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers", even_numbers)

Even Numbers [ 2  4  6  8 10]


### Filter with Mask

In [26]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])


Numbers greater than 5  [ 6  7  8  9 10]


### Fancy Indexing VS np.where()

In [28]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where: ", numbers[where_result])

[1 3 5]
NP where:  [ 6  7  8  9 10]


In [31]:
conditional_array = np.where(numbers>5, numbers*2, numbers)
print(conditional_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing Data

In [33]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

# combined_arr = arr_1+arr_2 >>>>> inaccurate way to do.
combined_arr = np.concatenate((arr_1, arr_2))
print(combined_arr)

[1 2 3 4 5 6]


### Array Compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibilty shapes: ", a.shape == b.shape)

Compatibilty shapes:  False


In [41]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

new_arr = np.vstack((original, new_row))
print(original)
print("------")
print(new_row)
print("------")
print(new_arr)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("------")
print(with_new_col)

[[1 2]
 [3 4]]
------
[[5 6]]
------
[[1 2]
 [3 4]
 [5 6]]
------
[[1 2 7]
 [3 4 8]]


In [44]:
k = np.array([1,2,3,4,5])

deleted = np.delete(k, 2)
print(deleted)

[1 2 4 5]
