## Learn Numpy

In [5]:
import numpy as np

### Creating Array From List

In [10]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List Versus Numpy Array

In [ ]:
py_list = [1,2,3]            # List wise multiplication
print("Python list multiplication", py_list*2)

np_array = np.array([1,2,3]) # Element wise multiplications
print("Python array multiplication", np_array*2)

import time
start = time.time()
py_list = [i*2  for i in range(1_00_00_00)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1_00_00_00) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time:  0.05143094062805176

 Numpy operation time:  0.0037567615509033203

 List operation time:  0.054099321365356445

 Numpy operation time:  0.0017316341400146484


### Creating array from scratch

In [19]:
zeroes = np.zeros((3, 4))
print("zeroes array: \n", zeroes)

ones = np.ones((4,5))
print("ones array: \n", ones)

full = np.full((2,2),7)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 13, 2)
print("sequence array: \n", sequence)

zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.41822081 0.12713312 0.63765571]
 [0.64001048 0.87870225 0.34941316]]
sequence array: 
 [ 0  2  4  6  8 10 12]


### Vector, Matrices, Tensor

In [20]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrices = np.array([[1,2,3],
                     [4,5,6]])
print("Matrices: ", matrices)

tensor = np.array([[[1,2,3], [4,5,6]], 
                   [[7,8,9],[10,11,12]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrices:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties

In [21]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape of array:", arr.shape)
print("Dimension of array:", arr.ndim)
print("Size of array:", arr.size)
print("Data Types array:", arr.dtype)

Shape of array: (2, 3)
Dimension of array: 2
Size of array: 6
Data Types array: int64


### Array Reshaping

In [34]:
arr = np.arange(12)
print("Original Array: ",arr)

reshaped_array = arr.reshape((3, 4))
print("\n Reshaped Array: \n", reshaped_array)

# It returns copy, not view
flattened = reshaped_array.flatten()
print("flattened Array: ", flattened)

raveled = flattened.ravel()
print("raveled Array: ", raveled)
# It returns view, not copy.

transpose = reshaped_array.T
print("transpose Array: ", transpose)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose Array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
